//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LibraryApplicationModel", "FK__SubTopicD__subto__1273C1CD", "SubTopics", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TestMvc4.Models.SubTopic), "SubTopicDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestMvc4.Models.SubTopicDetail), true)]
[assembly: EdmRelationshipAttribute("LibraryApplicationModel", "FK__SubTopics__index__0519C6AF", "Topics", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TestMvc4.Models.Topic), "SubTopics", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestMvc4.Models.SubTopic), true)]

#endregion

namespace TestMvc4.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LibraryApplicationEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LibraryApplicationEntities object using the connection string found in the 'LibraryApplicationEntities' section of the application configuration file.
        /// </summary>
        public LibraryApplicationEntities() : base("name=LibraryApplicationEntities", "LibraryApplicationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LibraryApplicationEntities object.
        /// </summary>
        public LibraryApplicationEntities(string connectionString) : base(connectionString, "LibraryApplicationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LibraryApplicationEntities object.
        /// </summary>
        public LibraryApplicationEntities(EntityConnection connection) : base(connection, "LibraryApplicationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SubTopicDetail> SubTopicDetails
        {
            get
            {
                if ((_SubTopicDetails == null))
                {
                    _SubTopicDetails = base.CreateObjectSet<SubTopicDetail>("SubTopicDetails");
                }
                return _SubTopicDetails;
            }
        }
        private ObjectSet<SubTopicDetail> _SubTopicDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SubTopic> SubTopics
        {
            get
            {
                if ((_SubTopics == null))
                {
                    _SubTopics = base.CreateObjectSet<SubTopic>("SubTopics");
                }
                return _SubTopics;
            }
        }
        private ObjectSet<SubTopic> _SubTopics;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Topic> Topics
        {
            get
            {
                if ((_Topics == null))
                {
                    _Topics = base.CreateObjectSet<Topic>("Topics");
                }
                return _Topics;
            }
        }
        private ObjectSet<Topic> _Topics;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SubTopicDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubTopicDetails(SubTopicDetail subTopicDetail)
        {
            base.AddObject("SubTopicDetails", subTopicDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SubTopics EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubTopics(SubTopic subTopic)
        {
            base.AddObject("SubTopics", subTopic);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Topics EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTopics(Topic topic)
        {
            base.AddObject("Topics", topic);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryApplicationModel", Name="SubTopic")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SubTopic : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SubTopic object.
        /// </summary>
        /// <param name="subtopicId">Initial value of the subtopicId property.</param>
        public static SubTopic CreateSubTopic(global::System.Int32 subtopicId)
        {
            SubTopic subTopic = new SubTopic();
            subTopic.subtopicId = subtopicId;
            return subTopic;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 subtopicId
        {
            get
            {
                return _subtopicId;
            }
            set
            {
                if (_subtopicId != value)
                {
                    OnsubtopicIdChanging(value);
                    ReportPropertyChanging("subtopicId");
                    _subtopicId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("subtopicId");
                    OnsubtopicIdChanged();
                }
            }
        }
        private global::System.Int32 _subtopicId;
        partial void OnsubtopicIdChanging(global::System.Int32 value);
        partial void OnsubtopicIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String subtopics
        {
            get
            {
                return _subtopics;
            }
            set
            {
                OnsubtopicsChanging(value);
                ReportPropertyChanging("subtopics");
                _subtopics = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("subtopics");
                OnsubtopicsChanged();
            }
        }
        private global::System.String _subtopics;
        partial void OnsubtopicsChanging(global::System.String value);
        partial void OnsubtopicsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> indexId
        {
            get
            {
                return _indexId;
            }
            set
            {
                OnindexIdChanging(value);
                ReportPropertyChanging("indexId");
                _indexId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("indexId");
                OnindexIdChanged();
            }
        }
        private Nullable<global::System.Int32> _indexId;
        partial void OnindexIdChanging(Nullable<global::System.Int32> value);
        partial void OnindexIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryApplicationModel", "FK__SubTopicD__subto__1273C1CD", "SubTopicDetails")]
        public EntityCollection<SubTopicDetail> SubTopicDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SubTopicDetail>("LibraryApplicationModel.FK__SubTopicD__subto__1273C1CD", "SubTopicDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SubTopicDetail>("LibraryApplicationModel.FK__SubTopicD__subto__1273C1CD", "SubTopicDetails", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryApplicationModel", "FK__SubTopics__index__0519C6AF", "Topics")]
        public Topic Topic
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Topic>("LibraryApplicationModel.FK__SubTopics__index__0519C6AF", "Topics").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Topic>("LibraryApplicationModel.FK__SubTopics__index__0519C6AF", "Topics").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Topic> TopicReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Topic>("LibraryApplicationModel.FK__SubTopics__index__0519C6AF", "Topics");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Topic>("LibraryApplicationModel.FK__SubTopics__index__0519C6AF", "Topics", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryApplicationModel", Name="SubTopicDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SubTopicDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SubTopicDetail object.
        /// </summary>
        /// <param name="stdID">Initial value of the stdID property.</param>
        public static SubTopicDetail CreateSubTopicDetail(global::System.Int32 stdID)
        {
            SubTopicDetail subTopicDetail = new SubTopicDetail();
            subTopicDetail.stdID = stdID;
            return subTopicDetail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stdID
        {
            get
            {
                return _stdID;
            }
            set
            {
                if (_stdID != value)
                {
                    OnstdIDChanging(value);
                    ReportPropertyChanging("stdID");
                    _stdID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("stdID");
                    OnstdIDChanged();
                }
            }
        }
        private global::System.Int32 _stdID;
        partial void OnstdIDChanging(global::System.Int32 value);
        partial void OnstdIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FACULTY
        {
            get
            {
                return _FACULTY;
            }
            set
            {
                OnFACULTYChanging(value);
                ReportPropertyChanging("FACULTY");
                _FACULTY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FACULTY");
                OnFACULTYChanged();
            }
        }
        private global::System.String _FACULTY;
        partial void OnFACULTYChanging(global::System.String value);
        partial void OnFACULTYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DURATION
        {
            get
            {
                return _DURATION;
            }
            set
            {
                OnDURATIONChanging(value);
                ReportPropertyChanging("DURATION");
                _DURATION = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DURATION");
                OnDURATIONChanged();
            }
        }
        private Nullable<global::System.Int32> _DURATION;
        partial void OnDURATIONChanging(Nullable<global::System.Int32> value);
        partial void OnDURATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> subtopicId
        {
            get
            {
                return _subtopicId;
            }
            set
            {
                OnsubtopicIdChanging(value);
                ReportPropertyChanging("subtopicId");
                _subtopicId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("subtopicId");
                OnsubtopicIdChanged();
            }
        }
        private Nullable<global::System.Int32> _subtopicId;
        partial void OnsubtopicIdChanging(Nullable<global::System.Int32> value);
        partial void OnsubtopicIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryApplicationModel", "FK__SubTopicD__subto__1273C1CD", "SubTopics")]
        public SubTopic SubTopic
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SubTopic>("LibraryApplicationModel.FK__SubTopicD__subto__1273C1CD", "SubTopics").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SubTopic>("LibraryApplicationModel.FK__SubTopicD__subto__1273C1CD", "SubTopics").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SubTopic> SubTopicReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SubTopic>("LibraryApplicationModel.FK__SubTopicD__subto__1273C1CD", "SubTopics");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SubTopic>("LibraryApplicationModel.FK__SubTopicD__subto__1273C1CD", "SubTopics", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryApplicationModel", Name="Topic")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Topic : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Topic object.
        /// </summary>
        /// <param name="topicId">Initial value of the topicId property.</param>
        public static Topic CreateTopic(global::System.Int32 topicId)
        {
            Topic topic = new Topic();
            topic.topicId = topicId;
            return topic;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 topicId
        {
            get
            {
                return _topicId;
            }
            set
            {
                if (_topicId != value)
                {
                    OntopicIdChanging(value);
                    ReportPropertyChanging("topicId");
                    _topicId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("topicId");
                    OntopicIdChanged();
                }
            }
        }
        private global::System.Int32 _topicId;
        partial void OntopicIdChanging(global::System.Int32 value);
        partial void OntopicIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String topics
        {
            get
            {
                return _topics;
            }
            set
            {
                OntopicsChanging(value);
                ReportPropertyChanging("topics");
                _topics = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("topics");
                OntopicsChanged();
            }
        }
        private global::System.String _topics;
        partial void OntopicsChanging(global::System.String value);
        partial void OntopicsChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryApplicationModel", "FK__SubTopics__index__0519C6AF", "SubTopics")]
        public EntityCollection<SubTopic> SubTopics
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SubTopic>("LibraryApplicationModel.FK__SubTopics__index__0519C6AF", "SubTopics");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SubTopic>("LibraryApplicationModel.FK__SubTopics__index__0519C6AF", "SubTopics", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
