//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace PatientInformation.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PatientEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PatientEntities object using the connection string found in the 'PatientEntities' section of the application configuration file.
        /// </summary>
        public PatientEntities() : base("name=PatientEntities", "PatientEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PatientEntities object.
        /// </summary>
        public PatientEntities(string connectionString) : base(connectionString, "PatientEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PatientEntities object.
        /// </summary>
        public PatientEntities(EntityConnection connection) : base(connection, "PatientEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Patient> Patients
        {
            get
            {
                if ((_Patients == null))
                {
                    _Patients = base.CreateObjectSet<Patient>("Patients");
                }
                return _Patients;
            }
        }
        private ObjectSet<Patient> _Patients;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Patients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPatients(Patient patient)
        {
            base.AddObject("Patients", patient);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PatientModel", Name="Patient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Patient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Patient object.
        /// </summary>
        /// <param name="patientId">Initial value of the patientId property.</param>
        public static Patient CreatePatient(global::System.Int32 patientId)
        {
            Patient patient = new Patient();
            patient.patientId = patientId;
            return patient;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 patientId
        {
            get
            {
                return _patientId;
            }
            set
            {
                if (_patientId != value)
                {
                    OnpatientIdChanging(value);
                    ReportPropertyChanging("patientId");
                    _patientId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("patientId");
                    OnpatientIdChanged();
                }
            }
        }
        private global::System.Int32 _patientId;
        partial void OnpatientIdChanging(global::System.Int32 value);
        partial void OnpatientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String patientName
        {
            get
            {
                return _patientName;
            }
            set
            {
                OnpatientNameChanging(value);
                ReportPropertyChanging("patientName");
                _patientName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("patientName");
                OnpatientNameChanged();
            }
        }
        private global::System.String _patientName;
        partial void OnpatientNameChanging(global::System.String value);
        partial void OnpatientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> patientAge
        {
            get
            {
                return _patientAge;
            }
            set
            {
                OnpatientAgeChanging(value);
                ReportPropertyChanging("patientAge");
                _patientAge = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("patientAge");
                OnpatientAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _patientAge;
        partial void OnpatientAgeChanging(Nullable<global::System.Int32> value);
        partial void OnpatientAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String note
        {
            get
            {
                return _note;
            }
            set
            {
                OnnoteChanging(value);
                ReportPropertyChanging("note");
                _note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("note");
                OnnoteChanged();
            }
        }
        private global::System.String _note;
        partial void OnnoteChanging(global::System.String value);
        partial void OnnoteChanged();

        #endregion

    
    }

    #endregion

    
}
